List<Map> gridCommonList = [
  {
    'image': 'chocolate.jpg',
    'name': 'All types Cake',
    'details': [
      {
        'image': 'chocolate.jpg',
        'id': '1',
        'Vname': 'Death by ChocolateCake',
        'offprice': '\$899',
        'price': '\$499',
        'off': '41% OFF',
        'star': 4,
        'delivary': 'Earlist Delivery \: Today',
      },
      {
        'image': 'BlackForest.jpg',
        'id': '2',
        'Vname': 'Yammylicious Choclate cake',
        'offprice': '\$689',
        'price': '\$549',
        'off': '21% OFF',
        'star': 3,
        'delivary': 'Earlist Delivery \: Today',
      },
      {
        'image': 'flower.jpg',
        'id': '3',
        'Vname': 'MixFlower Cake',
        'offprice': '\$1000',
        'price': '\$889',
        'off': '38% OFF',
        'star': 4,
        'delivary': 'Earlist Delivery \: Today',
      },
      {
        'image': 'photo.jpg',
        'id': '4',
        'Vname': 'PhotoPrint Cake',
        'offprice': '\$1500',
        'price': '\$999',
        'off': '50%Off',
        'star': 2,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'Designer.jpg',
        'id': '1',
        'Vname': 'Designer Cake',
        'offprice': '\$500',
        'price': '\$500',
        'off': '0 % OFF',
        'star': 5,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'heartShape.jpg',
        'id': '1',
        'Vname': 'Choco Alamond ',
        'offprice': '\$899',
        'price': '\$499',
        'off': '41%Off',
        'star': 1,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'combo.jpg',
        'id': '1',
        'Vname': 'Red Rose with Cake',
        'offprice': '\$2000',
        'price': '\$1999',
        'off': '41%Off',
        'star': 4,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'combo1.jpg',
        'id': '2',
        'Vname': 'Red flower with ChocolateCake',
        'offprice': '\$899',
        'price': '\$499',
        'off': '50%Off',
        'star': 1,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'combo2.jpg',
        'id': '3',
        'Vname': 'Ballon  and flower combo',
        'offprice': '\$2000',
        'price': '\$1999',
        'off': '10%Off',
        'star': 5,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'chocolate.jpg',
        'id': '1',
        'Vname': 'Death by ChocolateCake',
        'offprice': '\$899',
        'price': '\$499',
        'off': '41%Off',
        'star': 4,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'chocolate.jpg',
        'id': '1',
        'Vname': 'Death by ChocolateCake',
        'offprice': '\$899',
        'price': '\$499',
        'off': '41%Off',
        'star': 4,
        'delivary': 'Earliest Delivery \: Today',
      },
    ]
  },//all cake
  {
    'image': 'combo.jpg',
    'name': 'Perfect Combo',
    'details': [
      {
        'image': 'combo.jpg',
        'id': '1',
        'Vname': 'Red Rose with Cake',
        'offprice': '\$2000',
        'price': '\$1999',
        'off': '41%Off',
        'star': 4,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'combo1.jpg',
        'id': '2',
        'Vname': 'Red flower with ChocolateCake',
        'offprice': '\$899',
        'price': '\$499',
        'off': '50%Off',
        'star': 1,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'combo2.jpg',
        'id': '3',
        'Vname': 'Ballon  and flower combo',
        'offprice': '\$2000',
        'price': '\$1999',
        'off': '10%Off',
        'star': 5,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'combo3.jpg',
        'id': '1',
        'Vname': 'Tedday',
        'offprice': '\$999',
        'price': '\$555',
        'off': '50%Off',
        'star': 4,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'combo.jpg',
        'id': '1',
        'Vname': 'Red Rose with Cake',
        'offprice': '\$2000',
        'price': '\$1999',
        'off': '41%Off',
        'star': 4,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'combo1.jpg',
        'id': '2',
        'Vname': 'Red flower with ChocolateCake',
        'offprice': '\$899',
        'price': '\$499',
        'off': '50%Off',
        'star': 1,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'combo2.jpg',
        'id': '3',
        'Vname': 'Ballon  and flower combo',
        'offprice': '\$2000',
        'price': '\$1999',
        'off': '10%Off',
        'star': 5,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'combo.jpg',
        'id': '1',
        'Vname': 'Red Rose with Cake',
        'offprice': '\$2000',
        'price': '\$1999',
        'off': '41%Off',
        'star': 4,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'combo1.jpg',
        'id': '2',
        'Vname': 'Red flower with ChocolateCake',
        'offprice': '\$899',
        'price': '\$499',
        'off': '50%Off',
        'star': 1,
        'delivary': 'Earliest Delivery \: Today',
      },
    ]
  },// combo
  {
    'image': 'flower.jpg',
    'name': 'Fresh Flower\'S',
    'details': [
      {
        'image': 'flower1.jpg',
        'id': '1',
        'Vname': 'Pink Rose Bouquet',
        'offprice': '\$899',
        'price': '\$499',
        'off': '50%Off',
        'star': 5,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'flower.jpg',
        'id': '2',
        'Vname': 'Flower on cake',
        'offprice': '\$2000',
        'price': '\$999',
        'off': '60%Off',
        'star': 3,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'flower3.jpg',
        'id': '3',
        'Vname': 'Yellow rose love',
        'offprice': '\$3000',
        'price': '\$2500',
        'off': '20%Off',
        'star': 1,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'flower4.jpg',
        'id': '4',
        'Vname': 'pink love',
        'offprice': '\$899',
        'price': '\$499',
        'off': '50%Off',
        'star': 1,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'flower2.jpg',
        'id': '5',
        'Vname': 'Multi Colore Bouquet',
        'offprice': '\$899',
        'price': '\$499',
        'off': '50%Off',
        'star': 1,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'flower1.jpg',
        'id': '1',
        'Vname': 'Pink Rose Bouquet',
        'offprice': '\$899',
        'price': '\$499',
        'off': '50%Off',
        'star': 5,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'flower.jpg',
        'id': '2',
        'Vname': 'Flower on cake',
        'offprice': '\$2000',
        'price': '\$999',
        'off': '60%Off',
        'star': 3,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'flower3.jpg',
        'id': '3',
        'Vname': 'Yellow rose love',
        'offprice': '\$3000',
        'price': '\$2500',
        'off': '20%Off',
        'star': 1,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'flower4.jpg',
        'id': '4',
        'Vname': 'pink love',
        'offprice': '\$899',
        'price': '\$499',
        'off': '50%Off',
        'star': 1,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'flower2.jpg',
        'id': '5',
        'Vname': 'Multi Colore Bouquet',
        'offprice': '\$899',
        'price': '\$499',
        'off': '50%Off',
        'star': 1,
        'delivary': 'Earliest Delivery \: Today',
      },
    ]
  },// fresh flowers list
  {'image': 'gift3.jpg',
    'name': 'Personalised Gifts',
    'details':[
      {
        'image': 'gift3.jpg',
        'id': '1',
        'Vname': 'Gift for Love',
        'offprice': '\$2000',
        'price': '\$999',
        'off': '50%Off',
        'star': 5,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'gift.jpg',
        'id': '2',
        'Vname': 'Gift for baby',
        'offprice': '\$1000',
        'price': '\$999',
        'off': '0 %Off',
        'star': 2,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'gift1.jpg',
        'id': '3',
        'Vname': 'Perfect Ring ',
        'offprice': '\$5000',
        'price': '\$4000',
        'off': '20%Off',
        'star': 1,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'gift4.jpg',
        'id': '4',
        'Vname': 'Frame with photo',
        'offprice': '\$2000',
        'price': '\$999',
        'off': '50%Off',
        'star': 3,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'gift5.jpg',
        'id': '1',
        'Vname': 'Cup with label',
        'offprice': '\$500',
        'price': '\$200',
        'off': '50%Off',
        'star': 5,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'gift3.jpg',
        'id': '1',
        'Vname': 'Gift for Love',
        'offprice': '\$2000',
        'price': '\$999',
        'off': '50%Off',
        'star': 5,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'gift.jpg',
        'id': '2',
        'Vname': 'Gift for baby',
        'offprice': '\$1000',
        'price': '\$999',
        'off': '0 %Off',
        'star': 2,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'gift1.jpg',
        'id': '3',
        'Vname': 'Perfect Ring ',
        'offprice': '\$5000',
        'price': '\$4000',
        'off': '20%Off',
        'star': 1,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'gift4.jpg',
        'id': '4',
        'Vname': 'Frame with photo',
        'offprice': '\$2000',
        'price': '\$999',
        'off': '50%Off',
        'star': 3,
        'delivary': 'Earliest Delivery \: Today',
      },
      {
        'image': 'gift5.jpg',
        'id': '1',
        'Vname': 'Cup with label',
        'offprice': '\$500',
        'price': '\$200',
        'off': '50%Off',
        'star': 5,
        'delivary': 'Earliest Delivery \: Today',
      },


    ]
  },
  
];
